export BUILD_VER := RELEASE
export CXXFLAGS := -Wall -std=c++11
export RM := rm -f

.PHONY:all clean_all clean_all_cache

all:
	cd ./marm_visual_control && make

clean_all:
	cd ./marm_visual_control && make clean


clean_all_cache:
	cd ./marm_visual_control && make clean_cache

